version: '3'
services:
  db:
   image: mysql:latest
   container_name: mysqlDatabase
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=admin
     - MYSQL_DATABASE=portfolioDatabase
   volumes:
     - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_portfolio_app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=portfolioDatabase;user=root;password=admin

volumes:
  mysql_data: